export const RIDER_ASSIGNMENT_STATUS = {
  OFFERED: 'OFFERED',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  EXPIRED: 'EXPIRED',
  CANCELLED: 'CANCELLED',
  REASSIGNED: 'REASSIGNED',
} as const;

export type RiderAssignmentStatusValue =
  (typeof RIDER_ASSIGNMENT_STATUS)[keyof typeof RIDER_ASSIGNMENT_STATUS];
