export const CUISINE_TYPE = {
  NORTH_INDIAN: "NORTH_INDIAN",
  SOUTH_INDIAN: "SOUTH_INDIAN",
  CHINESE: "CHINESE",
  ITALIAN: "ITALIAN",
  MEXICAN: "MEXICAN",
  CONTINENTAL: "CONTINENTAL",
  FAST_FOOD: "FAST_FOOD",
  BAKERY: "BAKERY",
  DESSERTS: "DESSERTS",
  BEVERAGES: "BEVERAGES",
  SEAFOOD: "SEAFOOD",
  STREET_FOOD: "STREET_FOOD",
} as const;
export type CuisineType = (typeof CUISINE_TYPE)[keyof typeof CUISINE_TYPE]
