export const NOTIFICATION_CATEGORY = {
  ORDER_UPDATES: 'ORDER_UPDATES',
  DELIVERY: 'DELIVERY',
  SECURITY: 'SECURITY',
  PROMOTIONS: 'PROMOTIONS',
} as const;

export type NotificationCategoryValue = (typeof NOTIFICATION_CATEGORY)[keyof typeof NOTIFICATION_CATEGORY];
